"""empty message

Revision ID: 80424c8234c9
Revises: d565bdb23105
Create Date: 2020-12-11 15:22:31.052065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80424c8234c9'
down_revision = 'd565bdb23105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###
